connector:
  name: sree-docker
  identifier: sreedocker
  description: ""
  orgIdentifier: default
  projectIdentifier: salestestproject
  type: DockerRegistry
  spec:
    dockerRegistryUrl: test
    providerType: DockerHub
    auth:
      type: UsernamePassword
      spec:
        username: sreelk589
        passwordRef: docker
